apiVersion: v1
kind: Service
metadata:
  name: ui-srv
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8500
  selector:
    app:
     consul
    component:
     server
    release:
      consul
