---
- name: Stopping all the EC2 instances
  hosts: all
  gather_facts: false
  connection: local
  vars:
    instance_ids: 
     - "i-0fe1cd593a9a4725b"
     - "i-0472eaa3ea3e67c4c"
     - "i-01f4e5968baa3def0"
     - "i-0e4f09532e18c3100"
     - "i-0816df081224abf63"
     - "i-054e8ee333441a670"
    region: us-east-1
  tasks:
    - name: Stop instances 
      ec2:
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        state: stopped
        wait: True
        vpc_subnet_id: subnet-0b1efe3a
        assign_public_ip: yes
      
